version: '2'

services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: fuchtard
      POSTGRES_USER: fuchtard
      POSTGRES_DB: fuchtard
    ports:
      - 5432:5432
  nginx:
    image: nginx
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    volumes:
      - ./nginx.conf.template:/etc/nginx/conf.d/default.conf.template
      - ./uwsgi_params:/etc/nginx/uwsgi_params
    command: >
      /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PORT'
      < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf
      && cat /etc/nginx/conf.d/default.conf
      && nginx -g 'daemon off;'"
  backend:
    build: ./backend
    env_file: .env
    ports:
      - 8000:8000
    links:
      - db
    entrypoint: uwsgi --socket :8000 --module fuchtard.wsgi
  frontend:
    build: ./frontend
    environment:
      BACKEND_HOST: backend:8000
    ports:
      - 3000:3000
    command: npm run build