version: '2'

services:
  db:
    restart: always
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: fuchtard
      POSTGRES_USER: fuchtard
      POSTGRES_DB: fuchtard
    ports:
      - 5432:5432
  nginx:
    restart: always
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf.template:/etc/nginx/conf.d/default.conf.template
      - ./uwsgi_params:/etc/nginx/uwsgi_params
      - ./frontend/dist/.:/usr/src/app/dist
      - ./static_content/media/.:/usr/src/app/media
      - ./static_content/static/.:/usr/src/app/static
    command: >
      /bin/bash -c "envsubst '$$NGINX_HOST'
      < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf
      && nginx -g 'daemon off;'"
  backend:
    restart: always
    build: ./backend
    env_file: .env
    ports:
      - 8000:8000
    volumes:
      - ./static_content/media/.:/usr/src/static_content/media
    links:
      - db
    entrypoint: uwsgi --socket :8000 --module fuchtard.wsgi
  collectstatic:
    build: ./backend
    env_file: .env
    volumes:
      - ./static_content/static/.:/usr/src/static_content/static
    command: collectstatic --noinput
  frontend:
    image: node:7.9
    working_dir: /usr/src/app
    volumes:
      - ./frontend/.:/usr/src/app
    ports:
      - 3000:3000
    command: npm run build